CIC-IDS 2018

In [14]:
import pandas as pd
import pyarrow as pa

print("Python:", __import__("sys").version)
print("Pandas:", pd.__version__)
print("PyArrow:", pa.__version__)

Python: 3.14.0 (tags/v3.14.0:ebf955d, Oct  7 2025, 10:15:03) [MSC v.1944 64 bit (AMD64)]
Pandas: 3.0.2
PyArrow: 25.0.1

In [1]:
import pandas as pd
import pyarrow as pa

print("Pandas:", pd.__version__)
print("PyArrow:", pa.__version__)

test_file = "../data/raw/cicids18/Bruteforce-Wednesday-14-02-2018_TrafficForML_CICFlowMeter.parquet"

df = pd.read_parquet(test_file)

print("Shape:", df.shape)
print(df.columns.tolist())
display(df.head())

Pandas: 3.0.6
PyArrow: 25.0.1
Shape: (619346, 78)
['Protocol', 'Flow Duration', 'Total Fwd Packets', 'Total Backward Packets', 'Fwd Packets Length Total', 'Bwd Packets Length Total', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Packet Length Min', 'Packet Length Max', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio', 'Avg Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init Fwd Win Bytes', 'Init Bwd Win Bytes', 'Fwd Act Data Packets', 'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label']

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,112641719,3,0,0,0,0,0,0.000000,0.000000,...,0,0.0,0.0,0,0,56320860.0,139.300034,56320958,56320761,Benign
1,0,112641466,3,0,0,0,0,0,0.000000,0.000000,...,0,0.0,0.0,0,0,56320732.0,114.551300,56320814,56320652,Benign
2,0,112638623,3,0,0,0,0,0,0.000000,0.000000,...,0,0.0,0.0,0,0,56319312.0,301.934601,56319525,56319098,Benign
3,6,6453966,15,10,1239,2273,744,0,82.599998,196.741241,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign
4,6,8804066,14,11,1143,2209,744,0,81.642860,203.745544,...,32,0.0,0.0,0,0,0.0,0.000000,0,0,Benign

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

data_dir = Path("../data/raw/cicids18")

results = []

for file_path in sorted(data_dir.glob("*.parquet")):
    print(f"Auditing: {file_path.name}")

    df = pd.read_parquet(file_path)

    numeric_cols = df.select_dtypes(include=np.number).columns

    results.append({
        "file": file_path.name,
        "rows": len(df),
        "columns": len(df.columns),
        "missing_cells": int(df.isna().sum().sum()),
        "infinite_cells": int(np.isinf(df[numeric_cols]).sum().sum()),
        "duplicate_rows": int(df.duplicated().sum()),
        "label_column": "Label" if "Label" in df.columns else None,
        "unique_labels": df["Label"].nunique() if "Label" in df.columns else None,
    })

audit_2018 = pd.DataFrame(results)

display(audit_2018)

Auditing: Botnet-Friday-02-03-2018_TrafficForML_CICFlowMeter.parquet
Auditing: Bruteforce-Wednesday-14-02-2018_TrafficForML_CICFlowMeter.parquet
Auditing: DDoS1-Tuesday-20-02-2018_TrafficForML_CICFlowMeter.parquet
Auditing: DDoS2-Wednesday-21-02-2018_TrafficForML_CICFlowMeter.parquet
Auditing: DoS1-Thursday-15-02-2018_TrafficForML_CICFlowMeter.parquet
Auditing: DoS2-Friday-16-02-2018_TrafficForML_CICFlowMeter.parquet
Auditing: Infil1-Wednesday-28-02-2018_TrafficForML_CICFlowMeter.parquet
Auditing: Infil2-Thursday-01-03-2018_TrafficForML_CICFlowMeter.parquet
Auditing: Web1-Thursday-22-02-2018_TrafficForML_CICFlowMeter.parquet
Auditing: Web2-Friday-23-02-2018_TrafficForML_CICFlowMeter.parquet

,file,rows,columns,missing_cells,infinite_cells,duplicate_rows,label_column,unique_labels
0,Botnet-Friday-02-03-2018_TrafficForML_CICFlowM...,771587,78,0,0,0,Label,2
1,Bruteforce-Wednesday-14-02-2018_TrafficForML_C...,619346,78,0,0,0,Label,3
2,DDoS1-Tuesday-20-02-2018_TrafficForML_CICFlowM...,954846,78,0,0,0,Label,2
3,DDoS2-Wednesday-21-02-2018_TrafficForML_CICFlo...,561396,78,0,0,0,Label,3
4,DoS1-Thursday-15-02-2018_TrafficForML_CICFlowM...,794812,78,0,0,0,Label,3
5,DoS2-Friday-16-02-2018_TrafficForML_CICFlowMet...,591873,78,0,0,0,Label,3
6,Infil1-Wednesday-28-02-2018_TrafficForML_CICFl...,456873,78,0,0,0,Label,2
7,Infil2-Thursday-01-03-2018_TrafficForML_CICFlo...,249170,78,0,0,0,Label,2
8,Web1-Thursday-22-02-2018_TrafficForML_CICFlowM...,830224,78,0,0,0,Label,4
9,Web2-Friday-23-02-2018_TrafficForML_CICFlowMet...,829405,78,0,0,0,Label,4

In [5]:
df_2018 = pd.read_parquet(sorted(data_dir.glob("*.parquet"))[0])

print("Number of columns:", len(df_2018.columns))

for i, col in enumerate(df_2018.columns, start=1):
    print(f"{i:02d}. {repr(col)}")

Number of columns: 78
01. 'Protocol'
02. 'Flow Duration'
03. 'Total Fwd Packets'
04. 'Total Backward Packets'
05. 'Fwd Packets Length Total'
06. 'Bwd Packets Length Total'
07. 'Fwd Packet Length Max'
08. 'Fwd Packet Length Min'
09. 'Fwd Packet Length Mean'
10. 'Fwd Packet Length Std'
11. 'Bwd Packet Length Max'
12. 'Bwd Packet Length Min'
13. 'Bwd Packet Length Mean'
14. 'Bwd Packet Length Std'
15. 'Flow Bytes/s'
16. 'Flow Packets/s'
17. 'Flow IAT Mean'
18. 'Flow IAT Std'
19. 'Flow IAT Max'
20. 'Flow IAT Min'
21. 'Fwd IAT Total'
22. 'Fwd IAT Mean'
23. 'Fwd IAT Std'
24. 'Fwd IAT Max'
25. 'Fwd IAT Min'
26. 'Bwd IAT Total'
27. 'Bwd IAT Mean'
28. 'Bwd IAT Std'
29. 'Bwd IAT Max'
30. 'Bwd IAT Min'
31. 'Fwd PSH Flags'
32. 'Bwd PSH Flags'
33. 'Fwd URG Flags'
34. 'Bwd URG Flags'
35. 'Fwd Header Length'
36. 'Bwd Header Length'
37. 'Fwd Packets/s'
38. 'Bwd Packets/s'
39. 'Packet Length Min'
40. 'Packet Length Max'
41. 'Packet Length Mean'
42. 'Packet Length Std'
43. 'Packet Length Variance'
44. 'FIN Flag Count'
45. 'SYN Flag Count'
46. 'RST Flag Count'
47. 'PSH Flag Count'
48. 'ACK Flag Count'
49. 'URG Flag Count'
50. 'CWE Flag Count'
51. 'ECE Flag Count'
52. 'Down/Up Ratio'
53. 'Avg Packet Size'
54. 'Avg Fwd Segment Size'
55. 'Avg Bwd Segment Size'
56. 'Fwd Avg Bytes/Bulk'
57. 'Fwd Avg Packets/Bulk'
58. 'Fwd Avg Bulk Rate'
59. 'Bwd Avg Bytes/Bulk'
60. 'Bwd Avg Packets/Bulk'
61. 'Bwd Avg Bulk Rate'
62. 'Subflow Fwd Packets'
63. 'Subflow Fwd Bytes'
64. 'Subflow Bwd Packets'
65. 'Subflow Bwd Bytes'
66. 'Init Fwd Win Bytes'
67. 'Init Bwd Win Bytes'
68. 'Fwd Act Data Packets'
69. 'Fwd Seg Size Min'
70. 'Active Mean'
71. 'Active Std'
72. 'Active Max'
73. 'Active Min'
74. 'Idle Mean'
75. 'Idle Std'
76. 'Idle Max'
77. 'Idle Min'
78. 'Label'

In [3]:
df_2017 = pd.read_csv(
    "../data/raw/cicids17/Monday-WorkingHours.pcap_ISCX.csv",
    low_memory=False
)

In [6]:
cols_2017 = {col.strip() for col in df_2017.columns}
cols_2018 = set(df_2018.columns)

print("2017 columns:", len(cols_2017))
print("2018 columns:", len(cols_2018))

print("\nOnly in 2017:")
print(sorted(cols_2017 - cols_2018))

print("\nOnly in 2018:")
print(sorted(cols_2018 - cols_2017))

print("\nCommon columns:", len(cols_2017 & cols_2018))

2017 columns: 79
2018 columns: 78

Only in 2017:
['Average Packet Size', 'Destination Port', 'Fwd Header Length.1', 'Init_Win_bytes_backward', 'Init_Win_bytes_forward', 'Max Packet Length', 'Min Packet Length', 'Total Length of Bwd Packets', 'Total Length of Fwd Packets', 'act_data_pkt_fwd', 'min_seg_size_forward']

Only in 2018:
['Avg Packet Size', 'Bwd Packets Length Total', 'Fwd Act Data Packets', 'Fwd Packets Length Total', 'Fwd Seg Size Min', 'Init Bwd Win Bytes', 'Init Fwd Win Bytes', 'Packet Length Max', 'Packet Length Min', 'Protocol']

Common columns: 68

In [7]:
# Inspect the potentially mismatched features in both datasets

features_2017 = [
    'Average Packet Size',
    'Destination Port',
    'Fwd Header Length.1',
    'Init_Win_bytes_backward',
    'Init_Win_bytes_forward',
    'Max Packet Length',
    'Min Packet Length',
    'Total Length of Bwd Packets',
    'Total Length of Fwd Packets',
    'act_data_pkt_fwd',
    'min_seg_size_forward'
]

features_2018 = [
    'Avg Packet Size',
    'Bwd Packets Length Total',
    'Fwd Act Data Packets',
    'Fwd Packets Length Total',
    'Fwd Seg Size Min',
    'Init Bwd Win Bytes',
    'Init Fwd Win Bytes',
    'Packet Length Max',
    'Packet Length Min',
    'Protocol'
]

print("2017 feature dtypes and examples:")
print("=" * 60)

for col in features_2017:
    if col in df_2017.columns:
        print(f"\n{col}")
        print("dtype:", df_2017[col].dtype)
        print("unique:", df_2017[col].nunique())
        print(df_2017[col].head(3).tolist())


print("\n\n2018 feature dtypes and examples:")
print("=" * 60)

for col in features_2018:
    if col in df_2018.columns:
        print(f"\n{col}")
        print("dtype:", df_2018[col].dtype)
        print("unique:", df_2018[col].nunique())
        print(df_2018[col].head(3).tolist())

2017 feature dtypes and examples:
============================================================

Init_Win_bytes_forward
dtype: int64
unique: 5991
[329, 329, 329]

Total Length of Fwd Packets
dtype: int64
unique: 9511
[12, 12, 12]


2018 feature dtypes and examples:
============================================================

Avg Packet Size
dtype: float32
unique: 43072
[270.375, 25.33333396911621, 446.6538391113281]

Bwd Packets Length Total
dtype: float32
unique: 18066
[3773.0, 0.0, 10527.0]

Fwd Act Data Packets
dtype: int16
unique: 278
[4, 0, 5]

Fwd Packets Length Total
dtype: int32
unique: 6266
[553, 38, 1086]

Fwd Seg Size Min
dtype: int8
unique: 9
[20, 20, 20]

Init Bwd Win Bytes
dtype: int32
unique: 4725
[119, 0, 1047]

Init Fwd Win Bytes
dtype: int32
unique: 3799
[8192, 123, 8192]

Packet Length Max
dtype: int16
unique: 1186
[1460, 38, 1460]

Packet Length Min
dtype: int16
unique: 95
[0, 0, 0]

Protocol
dtype: int8
unique: 3
[6, 6, 6]

In [8]:
df_2017_clean_names = df_2017.copy()
df_2017_clean_names.columns = df_2017_clean_names.columns.str.strip()

features_2017 = [
    'Average Packet Size',
    'Destination Port',
    'Fwd Header Length.1',
    'Init_Win_bytes_backward',
    'Init_Win_bytes_forward',
    'Max Packet Length',
    'Min Packet Length',
    'Total Length of Bwd Packets',
    'Total Length of Fwd Packets',
    'act_data_pkt_fwd',
    'min_seg_size_forward'
]

for col in features_2017:
    if col in df_2017_clean_names.columns:
        print(f"\n{col}")
        print("dtype:", df_2017_clean_names[col].dtype)
        print("unique:", df_2017_clean_names[col].nunique())
        print(df_2017_clean_names[col].head(3).tolist())
    else:
        print(f"\nMISSING: {col}")

Average Packet Size
dtype: float64
unique: 60693
[9.0, 9.0, 9.0]

Destination Port
dtype: int64
unique: 30238
[49188, 49188, 49188]

Fwd Header Length.1
dtype: int64
unique: 1728
[40, 40, 40]

Init_Win_bytes_backward
dtype: int64
unique: 6262
[-1, -1, -1]

Init_Win_bytes_forward
dtype: int64
unique: 5991
[329, 329, 329]

Max Packet Length
dtype: int64
unique: 4401
[6, 6, 6]

Min Packet Length
dtype: int64
unique: 145
[6, 6, 6]

Total Length of Bwd Packets
dtype: int64
unique: 25014
[0, 0, 0]

Total Length of Fwd Packets
dtype: int64
unique: 9511
[12, 12, 12]

act_data_pkt_fwd
dtype: int64
unique: 553
[1, 1, 1]

min_seg_size_forward
dtype: int64
unique: 17
[20, 20, 20]

In [9]:
print("2017 Destination Port")
print(df_2017_clean_names["Destination Port"].describe())
print()

print("2017 Fwd Header Length.1")
print(df_2017_clean_names["Fwd Header Length.1"].describe())
print()

print("2018 Protocol")
print(df_2018["Protocol"].describe())
print()
print(df_2018["Protocol"].value_counts().sort_index())

2017 Destination Port
count    529918.000000
mean      10644.367112
std       21390.213475
min           0.000000
25%          53.000000
50%          80.000000
75%         443.000000
max       65535.000000
Name: Destination Port, dtype: float64

2017 Fwd Header Length.1
count    5.299180e+05
mean    -1.320351e+04
std      3.609256e+06
min     -1.929350e+09
25%      4.000000e+01
50%      6.400000e+01
75%      1.080000e+02
max      4.644908e+06
Name: Fwd Header Length.1, dtype: float64

2018 Protocol
count    771587.000000
mean          8.057785
std           4.486886
min           0.000000
25%           6.000000
50%           6.000000
75%           6.000000
max          17.000000
Name: Protocol, dtype: float64

Protocol
0      13094
6     607009
17    151484
Name: count, dtype: int64

Checking the constant values across 8 2017 files

In [13]:
candidate_features = [
    "Bwd PSH Flags",
    "Fwd URG Flags",
    "Bwd URG Flags",
    "CWE Flag Count",
    "Fwd Avg Bytes/Bulk",
    "Fwd Avg Packets/Bulk",
    "Fwd Avg Bulk Rate",
    "Bwd Avg Bytes/Bulk",
    "Bwd Avg Packets/Bulk",
    "Bwd Avg Bulk Rate"
]

global_values = {col: set() for col in candidate_features}

for file_path in files_2017:
    df = pd.read_csv(file_path, low_memory=False)
    df.columns = df.columns.str.strip()

    for col in candidate_features:
        global_values[col].update(df[col].dropna().unique())

for col, values in global_values.items():
    print(f"{col}: {len(values)} unique values -> {sorted(values)[:20]}")

Bwd PSH Flags: 1 unique values -> [np.int64(0)]
Fwd URG Flags: 2 unique values -> [np.int64(0), np.int64(1)]
Bwd URG Flags: 1 unique values -> [np.int64(0)]
CWE Flag Count: 2 unique values -> [np.int64(0), np.int64(1)]
Fwd Avg Bytes/Bulk: 1 unique values -> [np.int64(0)]
Fwd Avg Packets/Bulk: 1 unique values -> [np.int64(0)]
Fwd Avg Bulk Rate: 1 unique values -> [np.int64(0)]
Bwd Avg Bytes/Bulk: 1 unique values -> [np.int64(0)]
Bwd Avg Packets/Bulk: 1 unique values -> [np.int64(0)]
Bwd Avg Bulk Rate: 1 unique values -> [np.int64(0)]

In [15]:
from pathlib import Path
import pandas as pd

data_dir_2018 = Path("../data/raw/cicids18")
files_2018 = sorted(data_dir_2018.glob("*.parquet"))

candidate_features_2018 = [
    "Bwd PSH Flags",
    "Fwd URG Flags",
    "Bwd URG Flags",
    "CWE Flag Count",
    "Fwd Avg Bytes/Bulk",
    "Fwd Avg Packets/Bulk",
    "Fwd Avg Bulk Rate",
    "Bwd Avg Bytes/Bulk",
    "Bwd Avg Packets/Bulk",
    "Bwd Avg Bulk Rate"
]

global_values_2018 = {col: set() for col in candidate_features_2018}

for file_path in files_2018:
    df = pd.read_parquet(file_path)

    for col in candidate_features_2018:
        if col in df.columns:
            global_values_2018[col].update(df[col].dropna().unique())

for col, values in global_values_2018.items():
    print(f"{col}: {len(values)} unique values -> {sorted(values)[:20]}")

Bwd PSH Flags: 1 unique values -> [np.int8(0)]
Fwd URG Flags: 2 unique values -> [np.int8(0), np.int8(1)]
Bwd URG Flags: 1 unique values -> [np.int8(0)]
CWE Flag Count: 2 unique values -> [np.int8(0), np.int8(1)]
Fwd Avg Bytes/Bulk: 1 unique values -> [np.int8(0)]
Fwd Avg Packets/Bulk: 1 unique values -> [np.int8(0)]
Fwd Avg Bulk Rate: 1 unique values -> [np.int8(0)]
Bwd Avg Bytes/Bulk: 1 unique values -> [np.int8(0)]
Bwd Avg Packets/Bulk: 1 unique values -> [np.int8(0)]
Bwd Avg Bulk Rate: 1 unique values -> [np.int8(0)]

In [16]:
import numpy as np

remaining_features = [
    col for col in df_2017_clean_names.columns
    if col not in [
        "Label",
        "Destination Port",
        "Fwd Header Length.1",
        "Bwd PSH Flags",
        "Bwd URG Flags",
        "Fwd Avg Bytes/Bulk",
        "Fwd Avg Packets/Bulk",
        "Fwd Avg Bulk Rate",
        "Bwd Avg Bytes/Bulk",
        "Bwd Avg Packets/Bulk",
        "Bwd Avg Bulk Rate"
    ]
]

missing_inf_2017 = []

for file_path in files_2017:
    df = pd.read_csv(file_path, low_memory=False)
    df.columns = df.columns.str.strip()

    for col in remaining_features:
        missing = int(df[col].isna().sum())
        infinite = int(np.isinf(df[col]).sum())

        if missing > 0 or infinite > 0:
            missing_inf_2017.append({
                "file": file_path.name,
                "feature": col,
                "missing": missing,
                "infinite": infinite
            })

missing_inf_2017 = pd.DataFrame(missing_inf_2017)

display(missing_inf_2017)

,file,feature,missing,infinite
0,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,Flow Bytes/s,4,30
1,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,Flow Packets/s,0,34
2,Friday-WorkingHours-Afternoon-PortScan.pcap_IS...,Flow Bytes/s,15,356
3,Friday-WorkingHours-Afternoon-PortScan.pcap_IS...,Flow Packets/s,0,371
4,Friday-WorkingHours-Morning.pcap_ISCX.csv,Flow Bytes/s,28,94
5,Friday-WorkingHours-Morning.pcap_ISCX.csv,Flow Packets/s,0,122
6,Monday-WorkingHours.pcap_ISCX.csv,Flow Bytes/s,64,373
7,Monday-WorkingHours.pcap_ISCX.csv,Flow Packets/s,0,437
8,Thursday-WorkingHours-Afternoon-Infilteration....,Flow Bytes/s,18,189
9,Thursday-WorkingHours-Afternoon-Infilteration....,Flow Packets/s,0,207
10,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,Flow Bytes/s,20,115
11,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,Flow Packets/s,0,135
12,Tuesday-WorkingHours.pcap_ISCX.csv,Flow Bytes/s,201,63
13,Tuesday-WorkingHours.pcap_ISCX.csv,Flow Packets/s,0,264
14,Wednesday-workingHours.pcap_ISCX.csv,Flow Bytes/s,1008,289
15,Wednesday-workingHours.pcap_ISCX.csv,Flow Packets/s,0,1297

In [17]:
import numpy as np

missing_inf_2018 = []

for file_path in files_2018:
    df = pd.read_parquet(file_path)

    for col in remaining_features:
        if col in df.columns:
            missing = int(df[col].isna().sum())
            infinite = int(np.isinf(df[col]).sum())

            if missing > 0 or infinite > 0:
                missing_inf_2018.append({
                    "file": file_path.name,
                    "feature": col,
                    "missing": missing,
                    "infinite": infinite
                })

missing_inf_2018 = pd.DataFrame(missing_inf_2018)

display(missing_inf_2018)

Empty DataFrame
Columns: []
Index: []

In [18]:
import hashlib
import pandas as pd

duplicate_hashes_2017 = set()
seen_hashes_2017 = set()

for file_path in files_2017:
    df = pd.read_csv(file_path, low_memory=False)
    df.columns = df.columns.str.strip()

    row_hashes = pd.util.hash_pandas_object(df, index=False)

    current_hashes = set(row_hashes)
    duplicates = current_hashes & seen_hashes_2017

    duplicate_hashes_2017.update(duplicates)
    seen_hashes_2017.update(current_hashes)

    print(file_path.name, "cross-file duplicate hashes:", len(duplicates))

print("Total unique cross-file duplicate hashes:", len(duplicate_hashes_2017))

Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv cross-file duplicate hashes: 0
Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv cross-file duplicate hashes: 1525
Friday-WorkingHours-Morning.pcap_ISCX.csv cross-file duplicate hashes: 3952
Monday-WorkingHours.pcap_ISCX.csv cross-file duplicate hashes: 196
Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv cross-file duplicate hashes: 6942
Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv cross-file duplicate hashes: 7611
Tuesday-WorkingHours.pcap_ISCX.csv cross-file duplicate hashes: 11647
Wednesday-workingHours.pcap_ISCX.csv cross-file duplicate hashes: 20029
Total unique cross-file duplicate hashes: 33563

In [19]:
hash_labels_2017 = {}

for file_path in files_2017:
    df = pd.read_csv(file_path, low_memory=False)
    df.columns = df.columns.str.strip()

    row_hashes = pd.util.hash_pandas_object(df, index=False)

    for row_hash, label in zip(row_hashes, df["Label"]):
        if row_hash in duplicate_hashes_2017:
            hash_labels_2017.setdefault(row_hash, set()).add(label)

conflicting_duplicates_2017 = {
    row_hash: labels
    for row_hash, labels in hash_labels_2017.items()
    if len(labels) > 1
}

print("Cross-file duplicate hashes:", len(duplicate_hashes_2017))
print("Duplicates with conflicting labels:", len(conflicting_duplicates_2017))

Cross-file duplicate hashes: 33563
Duplicates with conflicting labels: 0

In [20]:
duplicate_hashes_2018 = set()
seen_hashes_2018 = set()

for file_path in files_2018:
    df = pd.read_parquet(file_path)

    row_hashes = pd.util.hash_pandas_object(df, index=False)

    current_hashes = set(row_hashes)
    duplicates = current_hashes & seen_hashes_2018

    duplicate_hashes_2018.update(duplicates)
    seen_hashes_2018.update(current_hashes)

    print(file_path.name, "cross-file duplicate hashes:", len(duplicates))

print("Total unique cross-file duplicate hashes:", len(duplicate_hashes_2018))

Botnet-Friday-02-03-2018_TrafficForML_CICFlowMeter.parquet cross-file duplicate hashes: 0
Bruteforce-Wednesday-14-02-2018_TrafficForML_CICFlowMeter.parquet cross-file duplicate hashes: 0
DDoS1-Tuesday-20-02-2018_TrafficForML_CICFlowMeter.parquet cross-file duplicate hashes: 12012
DDoS2-Wednesday-21-02-2018_TrafficForML_CICFlowMeter.parquet cross-file duplicate hashes: 0
DoS1-Thursday-15-02-2018_TrafficForML_CICFlowMeter.parquet cross-file duplicate hashes: 57654
DoS2-Friday-16-02-2018_TrafficForML_CICFlowMeter.parquet cross-file duplicate hashes: 0
Infil1-Wednesday-28-02-2018_TrafficForML_CICFlowMeter.parquet cross-file duplicate hashes: 36750
Infil2-Thursday-01-03-2018_TrafficForML_CICFlowMeter.parquet cross-file duplicate hashes: 19734
Web1-Thursday-22-02-2018_TrafficForML_CICFlowMeter.parquet cross-file duplicate hashes: 85079
Web2-Friday-23-02-2018_TrafficForML_CICFlowMeter.parquet cross-file duplicate hashes: 99182
Total unique cross-file duplicate hashes: 177415

In [21]:
hash_labels_2018 = {}

for file_path in files_2018:
    df = pd.read_parquet(file_path)

    row_hashes = pd.util.hash_pandas_object(df, index=False)

    for row_hash, label in zip(row_hashes, df["Label"]):
        if row_hash in duplicate_hashes_2018:
            hash_labels_2018.setdefault(row_hash, set()).add(label)

conflicting_duplicates_2018 = {
    row_hash: labels
    for row_hash, labels in hash_labels_2018.items()
    if len(labels) > 1
}

print("Cross-file duplicate hashes:", len(duplicate_hashes_2018))
print("Duplicates with conflicting labels:", len(conflicting_duplicates_2018))

Cross-file duplicate hashes: 177415
Duplicates with conflicting labels: 0

In [22]:
label_counts_2017 = []

for file_path in files_2017:
    df = pd.read_csv(file_path, low_memory=False)
    df.columns = df.columns.str.strip()

    counts = df["Label"].value_counts()

    for label, count in counts.items():
        label_counts_2017.append({
            "file": file_path.name,
            "label": label,
            "count": int(count)
        })

labels_2017 = pd.DataFrame(label_counts_2017)

display(labels_2017)

,file,label,count
0,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,DDoS,128027
1,Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv,BENIGN,97718
2,Friday-WorkingHours-Afternoon-PortScan.pcap_IS...,PortScan,158930
3,Friday-WorkingHours-Afternoon-PortScan.pcap_IS...,BENIGN,127537
4,Friday-WorkingHours-Morning.pcap_ISCX.csv,BENIGN,189067
5,Friday-WorkingHours-Morning.pcap_ISCX.csv,Bot,1966
6,Monday-WorkingHours.pcap_ISCX.csv,BENIGN,529918
7,Thursday-WorkingHours-Afternoon-Infilteration....,BENIGN,288566
8,Thursday-WorkingHours-Afternoon-Infilteration....,Infiltration,36
9,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,BENIGN,168186
10,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,Web Attack � Brute Force,1507
11,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,Web Attack � XSS,652
12,Thursday-WorkingHours-Morning-WebAttacks.pcap_...,Web Attack � Sql Injection,21
13,Tuesday-WorkingHours.pcap_ISCX.csv,BENIGN,432074
14,Tuesday-WorkingHours.pcap_ISCX.csv,FTP-Patator,7938
15,Tuesday-WorkingHours.pcap_ISCX.csv,SSH-Patator,5897
16,Wednesday-workingHours.pcap_ISCX.csv,BENIGN,440031
17,Wednesday-workingHours.pcap_ISCX.csv,DoS Hulk,231073
18,Wednesday-workingHours.pcap_ISCX.csv,DoS GoldenEye,10293
19,Wednesday-workingHours.pcap_ISCX.csv,DoS slowloris,5796
20,Wednesday-workingHours.pcap_ISCX.csv,DoS Slowhttptest,5499
21,Wednesday-workingHours.pcap_ISCX.csv,Heartbleed,11

In [23]:
label_counts_2018 = []

for file_path in files_2018:
    df = pd.read_parquet(file_path)

    counts = df["Label"].value_counts()

    for label, count in counts.items():
        label_counts_2018.append({
            "file": file_path.name,
            "label": label,
            "count": int(count)
        })

labels_2018 = pd.DataFrame(label_counts_2018)

display(labels_2018)

,file,label,count
0,Botnet-Friday-02-03-2018_TrafficForML_CICFlowM...,Benign,627052
1,Botnet-Friday-02-03-2018_TrafficForML_CICFlowM...,Bot,144535
2,Bruteforce-Wednesday-14-02-2018_TrafficForML_C...,Benign,525245
3,Bruteforce-Wednesday-14-02-2018_TrafficForML_C...,SSH-Bruteforce,94048
4,Bruteforce-Wednesday-14-02-2018_TrafficForML_C...,FTP-BruteForce,53
5,DDoS1-Tuesday-20-02-2018_TrafficForML_CICFlowM...,DDoS attacks-LOIC-HTTP,575364
6,DDoS1-Tuesday-20-02-2018_TrafficForML_CICFlowM...,Benign,379482
7,DDoS2-Wednesday-21-02-2018_TrafficForML_CICFlo...,Benign,360805
8,DDoS2-Wednesday-21-02-2018_TrafficForML_CICFlo...,DDOS attack-HOIC,198861
9,DDoS2-Wednesday-21-02-2018_TrafficForML_CICFlo...,DDOS attack-LOIC-UDP,1730
10,DoS1-Thursday-15-02-2018_TrafficForML_CICFlowM...,Benign,743498
11,DoS1-Thursday-15-02-2018_TrafficForML_CICFlowM...,DoS attacks-GoldenEye,41406
12,DoS1-Thursday-15-02-2018_TrafficForML_CICFlowM...,DoS attacks-Slowloris,9908
13,DoS2-Friday-16-02-2018_TrafficForML_CICFlowMet...,Benign,446619
14,DoS2-Friday-16-02-2018_TrafficForML_CICFlowMet...,DoS attacks-Hulk,145199
15,DoS2-Friday-16-02-2018_TrafficForML_CICFlowMet...,DoS attacks-SlowHTTPTest,55
16,Infil1-Wednesday-28-02-2018_TrafficForML_CICFl...,Benign,400424
17,Infil1-Wednesday-28-02-2018_TrafficForML_CICFl...,Infilteration,56449
18,Infil2-Thursday-01-03-2018_TrafficForML_CICFlo...,Benign,187136
19,Infil2-Thursday-01-03-2018_TrafficForML_CICFlo...,Infilteration,62034
20,Web1-Thursday-22-02-2018_TrafficForML_CICFlowM...,Benign,829883
21,Web1-Thursday-22-02-2018_TrafficForML_CICFlowM...,Brute Force -Web,228
22,Web1-Thursday-22-02-2018_TrafficForML_CICFlowM...,Brute Force -XSS,79
23,Web1-Thursday-22-02-2018_TrafficForML_CICFlowM...,SQL Injection,34
24,Web2-Friday-23-02-2018_TrafficForML_CICFlowMet...,Benign,828864
25,Web2-Friday-23-02-2018_TrafficForML_CICFlowMet...,Brute Force -Web,340
26,Web2-Friday-23-02-2018_TrafficForML_CICFlowMet...,Brute Force -XSS,150
27,Web2-Friday-23-02-2018_TrafficForML_CICFlowMet...,SQL Injection,51

In [24]:
common_feature_mapping = {
    "Average Packet Size": "Avg Packet Size",
    "Total Length of Bwd Packets": "Bwd Packets Length Total",
    "Total Length of Fwd Packets": "Fwd Packets Length Total",
    "act_data_pkt_fwd": "Fwd Act Data Packets",
    "min_seg_size_forward": "Fwd Seg Size Min",
    "Init_Win_bytes_backward": "Init Bwd Win Bytes",
    "Init_Win_bytes_forward": "Init Fwd Win Bytes",
    "Max Packet Length": "Packet Length Max",
    "Min Packet Length": "Packet Length Min"
}

features_2017_for_cross = [
    col for col in df_2017_clean_names.columns
    if col not in {
        "Label",
        "Destination Port",
        "Fwd Header Length.1",
        "Bwd PSH Flags",
        "Bwd URG Flags",
        "Fwd Avg Bytes/Bulk",
        "Fwd Avg Packets/Bulk",
        "Fwd Avg Bulk Rate",
        "Bwd Avg Bytes/Bulk",
        "Bwd Avg Packets/Bulk",
        "Bwd Avg Bulk Rate"
    }
]

features_2018_for_cross = []

for feature in features_2017_for_cross:
    if feature in common_feature_mapping:
        features_2018_for_cross.append(common_feature_mapping[feature])
    elif feature in df_2018.columns:
        features_2018_for_cross.append(feature)

print("2017 features:", len(features_2017_for_cross))
print("2018 features:", len(features_2018_for_cross))
print("Feature counts match:", len(features_2017_for_cross) == len(features_2018_for_cross))

2017 features: 68
2018 features: 68
Feature counts match: True

In [25]:
import hashlib
import numpy as np

def create_row_hashes(df, feature_columns):
    values = df[feature_columns].replace([np.inf, -np.inf], np.nan)
    values = values.fillna(0)
    values = values.astype(np.float64)

    hashes = pd.util.hash_pandas_object(
        values,
        index=False
    )

    return hashes

In [26]:
hashes_2017 = []

for file_path in files_2017:
    df = pd.read_csv(file_path)
    df.columns = df.columns.str.strip()

    for feature in features_2017_for_cross:
        if feature not in df.columns:
            raise ValueError(f"Missing feature in {file_path.name}: {feature}")

    row_hashes = create_row_hashes(df, features_2017_for_cross)

    hashes_2017.append(
        pd.DataFrame({
            "hash": row_hashes,
            "file": file_path.name
        })
    )

hashes_2017 = pd.concat(hashes_2017, ignore_index=True)

print("2017 hashed rows:", len(hashes_2017))
print("2017 unique hashes:", hashes_2017["hash"].nunique())

2017 hashed rows: 2830743
2017 unique hashes: 2233691

In [27]:
hashes_2018 = []

for file_path in files_2018:
    df = pd.read_parquet(file_path)

    for feature in features_2018_for_cross:
        if feature not in df.columns:
            raise ValueError(f"Missing feature in {file_path.name}: {feature}")

    row_hashes = create_row_hashes(df, features_2018_for_cross)

    hashes_2018.append(
        pd.DataFrame({
            "hash": row_hashes,
            "file": file_path.name
        })
    )

hashes_2018 = pd.concat(hashes_2018, ignore_index=True)

print("2018 hashed rows:", len(hashes_2018))
print("2018 unique hashes:", hashes_2018["hash"].nunique())

2018 hashed rows: 6659532
2018 unique hashes: 6297984

In [28]:
hashes_2017_unique = set(hashes_2017["hash"].unique())
hashes_2018_unique = set(hashes_2018["hash"].unique())

cross_dataset_duplicate_hashes = hashes_2017_unique.intersection(
    hashes_2018_unique
)

print(
    "Cross-dataset duplicate hashes:",
    len(cross_dataset_duplicate_hashes)
)

Cross-dataset duplicate hashes: 589

In [29]:
cross_2017 = hashes_2017[
    hashes_2017["hash"].isin(cross_dataset_duplicate_hashes)
].copy()

cross_2018 = hashes_2018[
    hashes_2018["hash"].isin(cross_dataset_duplicate_hashes)
].copy()

print("2017 rows with cross-dataset duplicate fingerprints:", len(cross_2017))
print("2018 rows with cross-dataset duplicate fingerprints:", len(cross_2018))

2017 rows with cross-dataset duplicate fingerprints: 3396
2018 rows with cross-dataset duplicate fingerprints: 2911

In [30]:
labels_by_hash_2017 = {}

for file_path in files_2017:
    df = pd.read_csv(file_path)
    df.columns = df.columns.str.strip()

    row_hashes = create_row_hashes(df, features_2017_for_cross)

    temp = pd.DataFrame({
        "hash": row_hashes,
        "label": df["Label"].values
    })

    temp = temp[temp["hash"].isin(cross_dataset_duplicate_hashes)]

    for hash_value, group in temp.groupby("hash"):
        labels_by_hash_2017[hash_value] = group["label"].unique().tolist()

print("2017 shared fingerprints with labels:", len(labels_by_hash_2017))

2017 shared fingerprints with labels: 589

In [31]:
labels_by_hash_2018 = {}

for file_path in files_2018:
    df = pd.read_parquet(file_path)

    row_hashes = create_row_hashes(df, features_2018_for_cross)

    temp = pd.DataFrame({
        "hash": row_hashes,
        "label": df["Label"].values
    })

    temp = temp[temp["hash"].isin(cross_dataset_duplicate_hashes)]

    for hash_value, group in temp.groupby("hash"):
        labels_by_hash_2018[hash_value] = group["label"].unique().tolist()

print("2018 shared fingerprints with labels:", len(labels_by_hash_2018))

2018 shared fingerprints with labels: 589

In [32]:
def to_binary_label(label):
    return "BENIGN" if str(label).strip().upper() == "BENIGN" else "ATTACK"

conflicting_binary_labels = []

for hash_value in cross_dataset_duplicate_hashes:
    labels_2017 = {
        to_binary_label(label)
        for label in labels_by_hash_2017[hash_value]
    }

    labels_2018 = {
        to_binary_label(label)
        for label in labels_by_hash_2018[hash_value]
    }

    if labels_2017 != labels_2018:
        conflicting_binary_labels.append({
            "hash": hash_value,
            "2017_labels": labels_2017,
            "2018_labels": labels_2018
        })

print("Cross-dataset fingerprints with conflicting binary labels:",
      len(conflicting_binary_labels))

Cross-dataset fingerprints with conflicting binary labels: 22

In [33]:
conflict_df = pd.DataFrame(conflicting_binary_labels)

display(conflict_df)

                    hash 2017_labels       2018_labels
0    6405239764317511743    {BENIGN}  {ATTACK, BENIGN}
1    2629853661352794327    {BENIGN}  {ATTACK, BENIGN}
2   12277123650959091954    {BENIGN}          {ATTACK}
3   15077862550532241784    {BENIGN}  {ATTACK, BENIGN}
4    5630322898142364094    {BENIGN}  {ATTACK, BENIGN}
5    4112859790121437772    {BENIGN}  {ATTACK, BENIGN}
6   10926698957024524887    {BENIGN}  {ATTACK, BENIGN}
7     157560124370432776    {BENIGN}  {ATTACK, BENIGN}
8   12376717946338466626    {BENIGN}  {ATTACK, BENIGN}
9   10578696721398334285    {BENIGN}  {ATTACK, BENIGN}
10  14599347634980576234    {BENIGN}  {ATTACK, BENIGN}
11   6412572112151487540    {BENIGN}  {ATTACK, BENIGN}
12   6211172208847535249    {BENIGN}  {ATTACK, BENIGN}
13  13266620366110201004    {BENIGN}  {ATTACK, BENIGN}
14  15809627585704195394    {BENIGN}  {ATTACK, BENIGN}
15  12303032539324523939    {BENIGN}  {ATTACK, BENIGN}
16   9148784158941871659    {BENIGN}  {ATTACK, BENIGN}
17   2400447232436065873    {BENIGN}          {ATTACK}
18  13924718052355884698    {BENIGN}          {ATTACK}
19   2404057054698493611    {BENIGN}          {ATTACK}
20  16826933329343456968    {BENIGN}  {ATTACK, BENIGN}
21   9629944760750327548    {BENIGN}  {ATTACK, BENIGN}

In [34]:
test = pd.DataFrame({
    "x": [0.0, np.nan, np.inf, -np.inf]
})

test_hashes = pd.util.hash_pandas_object(
    test,
    index=False
)

print(test)
print()
print(test_hashes)
print()
print("Unique hashes:", test_hashes.nunique())

     x
0  0.0
1  NaN
2  inf
3 -inf

0           3430018387555
1    16887603562957652324
2      402709737223303923
3    18168152695897012968
dtype: uint64

Unique hashes: 4

In [35]:
def create_row_hashes(df, feature_columns):
    values = df[feature_columns].astype(np.float64)

    hashes = pd.util.hash_pandas_object(
        values,
        index=False
    )

    return hashes

In [37]:
hashes_2017 = pd.concat(
    [
        pd.DataFrame({
            "hash": create_row_hashes(
                pd.read_csv(file).rename(columns=lambda x: x.strip()),
                features_2017_for_cross
            ),
            "file": file.name
        })
        for file in files_2017
    ],
    ignore_index=True
)

hashes_2018 = pd.concat(
    [
        pd.DataFrame({
            "hash": create_row_hashes(
                pd.read_parquet(file),
                features_2018_for_cross
            ),
            "file": file.name
        })
        for file in files_2018
    ],
    ignore_index=True
)

print("2017 fingerprints:", len(hashes_2017))
print("2018 fingerprints:", len(hashes_2018))

2017 fingerprints: 2830743
2018 fingerprints: 6659532

In [38]:
shared_hashes = set(hashes_2017["hash"]).intersection(
    set(hashes_2018["hash"])
)

print("Shared fingerprints:", len(shared_hashes))

Shared fingerprints: 589

In [39]:
labels_by_hash_2017 = (
    pd.concat(
        [
            pd.DataFrame({
                "hash": create_row_hashes(
                    pd.read_csv(file).rename(columns=lambda x: x.strip()),
                    features_2017_for_cross
                ),
                "label": pd.read_csv(file)[" Label"].astype(str).str.strip()
            })
            for file in files_2017
        ],
        ignore_index=True
    )
)

labels_by_hash_2018 = (
    pd.concat(
        [
            pd.DataFrame({
                "hash": create_row_hashes(
                    pd.read_parquet(file),
                    features_2018_for_cross
                ),
                "label": pd.read_parquet(file)["Label"].astype(str).str.strip()
            })
            for file in files_2018
        ],
        ignore_index=True
    )
)

labels_by_hash_2017 = labels_by_hash_2017[
    labels_by_hash_2017["hash"].isin(shared_hashes)
]

labels_by_hash_2018 = labels_by_hash_2018[
    labels_by_hash_2018["hash"].isin(shared_hashes)
]

print("2017 shared rows:", len(labels_by_hash_2017))
print("2018 shared rows:", len(labels_by_hash_2018))

2017 shared rows: 3396
2018 shared rows: 2911

In [41]:
def to_binary_label(label):
    return "BENIGN" if label.strip().upper() == "BENIGN" else "ATTACK"

labels_by_hash_2017["binary_label"] = labels_by_hash_2017["label"].map(to_binary_label)
labels_by_hash_2018["binary_label"] = labels_by_hash_2018["label"].map(to_binary_label)

binary_labels_2017 = (
    labels_by_hash_2017
    .groupby("hash")["binary_label"]
    .apply(set)
)

binary_labels_2018 = (
    labels_by_hash_2018
    .groupby("hash")["binary_label"]
    .apply(set)
)

conflicting_hashes = [
    h for h in shared_hashes
    if binary_labels_2017.get(h, set()) != binary_labels_2018.get(h, set())
]

print("Conflicting fingerprints:", len(conflicting_hashes))

Conflicting fingerprints: 190

In [42]:
conflict_summary = pd.DataFrame({
    "hash": conflicting_hashes,
    "2017_labels": [binary_labels_2017[h] for h in conflicting_hashes],
    "2018_labels": [binary_labels_2018[h] for h in conflicting_hashes]
})

print(conflict_summary["2017_labels"].value_counts().to_string())
print()
print(conflict_summary["2018_labels"].value_counts().to_string())

2017_labels
{BENIGN}    190

2018_labels
{ATTACK, BENIGN}    189
{ATTACK}              1

In [45]:
comparison = pd.DataFrame({
    "2017": match_2017.iloc[0],
    "2018": match_2018.iloc[0]
})

comparison = comparison[
    comparison["2017"].astype(str) != comparison["2018"].astype(str)
]

print(comparison.to_string())

                                  2017           2018
Average Packet Size                0.0            NaN
Avg Packet Size                    NaN            0.0
Bwd Packets Length Total           NaN              0
Destination Port                 55614            NaN
Fwd Act Data Packets               NaN              0
Fwd Header Length.1                 40            NaN
Fwd Packets Length Total           NaN              0
Fwd Packets/s                2000000.0      2000000.0
Fwd Seg Size Min                   NaN             20
Init Bwd Win Bytes                 NaN             -1
Init Fwd Win Bytes                 NaN            444
Init_Win_bytes_backward             -1            NaN
Init_Win_bytes_forward             444            NaN
Label                           BENIGN  Infilteration
Max Packet Length                    0            NaN
Min Packet Length                    0            NaN
Packet Length Max                  NaN              0
Packet Length Min                  NaN              0
Protocol                           NaN              6
Total Length of Bwd Packets          0            NaN
Total Length of Fwd Packets          0            NaN
act_data_pkt_fwd                     0            NaN
min_seg_size_forward                20            NaN